"""
This is a setup.py script generated by py2app

Usage:
    python3 setup.py py2app
"""
from setuptools import setup

APP = ['markdown_cleaner_app.py']
APP_NAME = "Markdown Cleaner"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'app_icon.icns', # Optional: create an icon for your app
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Cleans escaped markdown characters",
        'CFBundleIdentifier': "com.yourdomain.markdowncleaner", # Change this
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, Your Name. All Rights Reserved" # Change this
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)